language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.8
node_js:
  - "6.10.0-"
before_install:
  - npm -g install npm@next
  - npm install
  - nvm install 6.10
  - npm rebuild node-sass
  - npm --version
  - node --version
before_script:
  - sleep 15
  - mongo test --eval 'db.addUser("travis", "test");'

notifications:
    email:
        recipients:
            - ben.minderhoud@gmail.com
        on_success: change
        on_failure: always
services:
- mongodb
