language: scala
jdk:
  - oraclejdk8
scala:
  - 2.11.8
node_js:
  - "6.10.0-"
before_install:
  - npm -g install npm@next
  - npm install
  - nvm install 6.10
  - npm rebuild node-sass
  - npm --version
  - node --version
before_script:
  - sleep 15
  - mongo test --eval 'db.addUser("travis", "test");'
  - export PHANTOMJS_BIN=/usr/local/phantomjs/bin/phantomjs

after_script:
  - ls /home/travis/build/bminderh/play-react-webpack/*
  - ls /home/travis/build/bminderh/play-react-webpack/app/assets/*
  - ls /home/travis/build/bminderh/play-react-webpack/app/assets/javascripts/*



notifications:
    email:
        recipients:
            - ben.minderhoud@gmail.com
        on_success: change
        on_failure: always
services:
- mongodb
